[package]
name = "light"
version = "0.0.2"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
image = "0.25.10"
glm = { version = "0.21.0", package = "nalgebra-glm" }
rand = "0.10.1"
rand_distr = "0.6.0"
rayon = "1.12.0"
